spring:
  datasource:
    url: jdbc:mysql://192.168.2.15:13306/passbook
    password: root
    username: root
  kafka:
    bootstrap-servers:
      - 192.168.2.15:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
server:
  port: 9527

logging:
  level:
    root: INFO
  path: log